name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-generate-rpm
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-generate-rpm
      - name: Build
        run: cargo build --release
      - name: Strip
        run: strip -s target/release/browserdemux
      - name: Package into RPM
        run: cargo generate-rpm
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64.rpm
          path: 'target/generate-rpm/browserdemux-*.rpm'
  
  release:
    runs-on: ubuntu-latest
    needs: [rpm]
    permissions:
      contents: write
    steps:
      - uses: softprops/action-gh-release@v2
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        name: Create release
        with:
          files: '*/browserdemux-*.rpm'
